export const TOKEN_APP_INITIALISED = 'TOKEN_APP_INITIALISED'
export const TOKEN_INCREMENT = 'TOKEN_INCREMENT'
export const TOKEN_DECREMENT = 'TOKEN_DECREMENT'

export const DEMO_STORE = 'DEMO_STORE'

export const DEMO_VIEWCONTAINER = 'DEMO_VIEWCONTAINER'

export const ACTION_APP = 'ACTION_APP'
export const ACTION_DEMO = 'ACTION_DEMO'
